name: Checks and Validation
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 26
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Generate svelte data
        run: |
          npm run sync

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}

      - name: Run linters
        uses: profiidev/rust-lint-action@6592fe2b81f52c155bc416c51b6a860196a96f48 # v4
        with:
          auto_fix: true
          svelte: true
          oxlint: true
          oxfmt: true
          git_sign_commits: true
          github_token: ${{ steps.app-token.outputs.token }}

  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 26
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Generate svelte data
        run: |
          npm run sync

      - name: Build project
        run: |
          npm run build
